runtime: python312

instance_class: F2

# env_variables:
#   BUCKET_NAME: "example-gcs-bucket"

# handlers:
# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto
entrypoint: gunicorn --bind :$PORT -k uvicorn.workers.UvicornWorker app.main:app

