services: 
  app:
    image: nilofe/test-cev:main
    ports:
      - "8000:8000"
    networks:
      - app-net

  nginx:
    container_name: nginx
    restart: always
    build: 
      context: ./jobs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-net

 
networks:
  app-net: