apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion-python
  labels:
    app: pydev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pydev
  template:
    metadata:
      labels:
        app: pydev
    spec:
      containers:
      - name: mi-aplicacion-python
        image: nilofe/test-challege-ia:main
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mipok-svc
spec:
  selector:
    app.kubernetes.io/name: pydev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer