name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'World'
jobs:
  hello:
      runs-on: ubuntu-latest

      steps:
      - name: Hello steps
        run: echo "Hello ${{ github.event.inputs.name }}"