on:
  workflow_dispatch:
  push:
    branches:
      - main

name: build
permissions:
  contents: read
  packages: write  # Update this to provide the required permissions for the nested job
  id-token: write
  
 
jobs:
  build:
    uses: ./.github/workflows/test.yaml
    if: github.ref == 'refs/heads/main'
    with:
      registryUsername: ${{ secrets.REGISTRY_USER }}
      registryPassword: ${{ secrets.REGISTRY_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo
      
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTEST01_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTEST01_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTEST01_AZURE_SUBSCRIPTION_ID }}
  
      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername:  ${{ secrets.REGISTRY_USER }}
          registryPassword: ${{ secrets.REGISTRY_TOKEN }}
          containerAppName: aca-01-newtest
          resourceGroup: RSG-01
          imageToBuild: nilofe/test-dev:latest
          _buildArgumentsKey_: |
            _buildArgumentsValues_


