name: Run Tests
'on':
  push:
    branches:
      - release
  pull_request:
    branches:
      - main
env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  GCP_PROJECT_ID: dev-a-408722
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest tests/
  push-build-image-docker:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: extract metadata (tags, labels) for docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: build and push docker image 1
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: build and push docker image 2 
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./jobs
          push: true
          tags: nilofe/nginx-cert
          labels: |
            com.example.version=my-version
            com.example.build-date=2024-01-17

  deploy:
    needs: push-build-image-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name:  Authenticate with Google Cloud
        id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          service_account: dev-a-408722@appspot.gserviceaccount.com
          create_credentials_file: false
          run: |
            gcloud auth login

      # - name: Deploy to app engine
      #   id: 'deploy'
      #   uses: 'google-github-actions/deploy-appengine@v2'
      #   with:
      #     project_id: ${{ env.GCP_PROJECT_ID }}
      #     deliverables: './app.yaml'

      # - id: 'test'
      #   run: 'curl "${{ steps.deploy.outputs.version_url }}"'